apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-petclinic
  annotations:
    github.com/project-slug: hw038/spring-petclinic
spec:
  type: Service
  lifecycle: experimental
  owner: guests
